plugins {
	id 'fabric-loom' version '1.7-SNAPSHOT'
    id "de.undercouch.download" version "4.1.2"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version + "+" + project.minecraft_version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	from("LICENSE")
}

afterEvaluate {
    download {
        src "https://weblate.ziyuesinicization.site/api/components/filters-api/en_us-json/file/"
        dest "lang.zip"
        overwrite true
        retries - 1
    }
    copy {
        from(zipTree("lang.zip"))
        into "temp_lang"
    }
    copy {
        from "temp_lang/filters-api/en_us-json/"
        into "."
    }
    delete("lang.zip", "temp_lang")
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name + "-fabric"
            version = project.mod_version + "+" + project.minecraft_version
			from components.java
		}
	}

	repositories {
        maven {
            url = "https://maven.ziyuesinicization.site/releases/"
            credentials {
                username = "ZiYueCommentary"
                password = System.getenv("MAVEN_PASS")
            }
        }
	}
}