# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
parchment_minecraft_version=1.21.4
parchment_mappings_version=2025.03.23
minecraft_version=1.21.4
minecraft_version_range=[1.21.4]
neo_version=21.4.157
loader_version_range=[1,)

## Mod Properties
mod_id=filters
mod_name=Filters API
mod_license=MIT
mod_version=1.1.0
mod_group_id=ziyue
mod_authors=ZiYueCommentary
mod_description=Provides a filtering system to creative mode tabs.

maven_group=ziyue.filters
archives_base_name=filters