org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.18.2
minecraft_version_range=[1.18.2,1.19)
forge_version=40.2.0
forge_version_range=[40,)
loader_version_range=[40,)
mapping_channel=official
mapping_version=1.18.2

mod_id=filters
mod_name=Filters API
mod_license=MIT
mod_version=1.0.0
mod_group_id=ziyue
mod_authors=ZiYueCommentary
mod_description=Provides a filtering system to creative mode tabs.

maven_group=ziyue.filters
archives_base_name=filters